//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServis1.KlijentAplikacija {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KlijentAplikacija.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name con from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Convert", ReplyAction="*")]
        WebServis1.KlijentAplikacija.ConvertResponse Convert(WebServis1.KlijentAplikacija.ConvertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Convert", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServis1.KlijentAplikacija.ConvertResponse> ConvertAsync(WebServis1.KlijentAplikacija.ConvertRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Convert", Namespace="http://tempuri.org/", Order=0)]
        public WebServis1.KlijentAplikacija.ConvertRequestBody Body;
        
        public ConvertRequest() {
        }
        
        public ConvertRequest(WebServis1.KlijentAplikacija.ConvertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float val;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string con;
        
        public ConvertRequestBody() {
        }
        
        public ConvertRequestBody(float val, string con) {
            this.val = val;
            this.con = con;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServis1.KlijentAplikacija.ConvertResponseBody Body;
        
        public ConvertResponse() {
        }
        
        public ConvertResponse(WebServis1.KlijentAplikacija.ConvertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float ConvertResult;
        
        public ConvertResponseBody() {
        }
        
        public ConvertResponseBody(float ConvertResult) {
            this.ConvertResult = ConvertResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebServis1.KlijentAplikacija.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebServis1.KlijentAplikacija.WebService1Soap>, WebServis1.KlijentAplikacija.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServis1.KlijentAplikacija.ConvertResponse WebServis1.KlijentAplikacija.WebService1Soap.Convert(WebServis1.KlijentAplikacija.ConvertRequest request) {
            return base.Channel.Convert(request);
        }
        
        public float Convert(float val, string con) {
            WebServis1.KlijentAplikacija.ConvertRequest inValue = new WebServis1.KlijentAplikacija.ConvertRequest();
            inValue.Body = new WebServis1.KlijentAplikacija.ConvertRequestBody();
            inValue.Body.val = val;
            inValue.Body.con = con;
            WebServis1.KlijentAplikacija.ConvertResponse retVal = ((WebServis1.KlijentAplikacija.WebService1Soap)(this)).Convert(inValue);
            return retVal.Body.ConvertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServis1.KlijentAplikacija.ConvertResponse> WebServis1.KlijentAplikacija.WebService1Soap.ConvertAsync(WebServis1.KlijentAplikacija.ConvertRequest request) {
            return base.Channel.ConvertAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServis1.KlijentAplikacija.ConvertResponse> ConvertAsync(float val, string con) {
            WebServis1.KlijentAplikacija.ConvertRequest inValue = new WebServis1.KlijentAplikacija.ConvertRequest();
            inValue.Body = new WebServis1.KlijentAplikacija.ConvertRequestBody();
            inValue.Body.val = val;
            inValue.Body.con = con;
            return ((WebServis1.KlijentAplikacija.WebService1Soap)(this)).ConvertAsync(inValue);
        }
    }
}
